-- Drop tables in reverse order of creation
DROP TABLE IF EXISTS TRIP_TRANSPORTATION;
DROP TABLE IF EXISTS Location_Trip;
DROP TABLE IF EXISTS TRIP_EQUIPMENT;
DROP TABLE IF EXISTS REGISTERS_TO;
DROP TABLE IF EXISTS EQUIPMENT;
DROP TABLE IF EXISTS TRANSPORTATION;
DROP TABLE IF EXISTS SUPPLIER;
DROP TABLE IF EXISTS PARTICIPANT;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS TRIP;
